### ISSUE TITLE
Potential issue in extractMdxHeadings function

### ISSUE THREAD

**Issue by cheesyMan** [bonnie/howd-mdx-toc#7]
Hi @bonnie,
I just started the MDX series of challenges (I had to study MDX a little bit before... 🙃).

I think the `extractMdxHeadings` function has a little hidden issue as it is shown in the solution:

```
export function extractMdxHeadings(mdxContent: string): Array<HeadingData> {
  const headings: Array<HeadingData> = [];

  // match the `#` syntax for headings
  const headingMatcher = /^(#+)\s(.+)$/gm;
  let match = headingMatcher.exec(mdxContent);

  while (match !== null) {
    const level = match[1].length;
    const title = match[2].trim();

    if (level === 2 || level === 3) {
      // record this heading
      headings.push({ title, level });

     // get next match
     match = headingMatcher.exec(mdxContent); // <-- POTENTIAL ISSUE
    }
  }

  return headings;
}
```

As the get-next-match line is inside the `if()` check, it could lead to the **while** loop never ending if there are headings different from level 2 or level 3 in the mdx file.

In that case, the new `regex.exec()` would never be called again, the `match` variable would never end to be null and the loop would never finish.
The articles from the challenge don't have any heading different from 2|3 level so the issue is not noticeable, but if you add one, the page will not load anymore and the PC fans will start to increase RPM.

The solution, as I can see, is to move the get-next-match line outside the `if()` check.

Let me know if I'm right and thanks for your challenging challenges (pun intended 😊)

**Comment by bonnie** [comment]
Great catch, Alberto! I have corrected this in the [solution post](https://newsletter.howd.dev/solutions/009/#step-1-write-the-function-to-extract-headings) and the [GitHub code](https://github.com/bonnie/howd-mdx-toc/pull/1/files#diff-1916221ec74c766fd21b3e7dfca2df7f666aa10f5853dad23f62a6de90a082aa). 

I'm also very glad to hear you're enjoying the challenges. 😄
